version: "3.7"
services:

  rate-service:
    build:
      context: ./services/rate-service
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - "5000:5000"
    networks:
      - ts-network

  subscription-service:
    build:
      context: ./services/email-service
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - ts-network

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_DEFAULT_USER=username"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge