export const Ports = {
    EMAIL_SERVER_PORT: process.env.EMAIL_SERVER_PORT || 3000,
    RATE_SERVER_PORT: process.env.EMAIL_SERVER_PORT || 5000,
    CUSTOMER_SERVER_PORT: process.env.CUSTOMER_SERVER_PORT || 8082,
}